// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action ArchivoAction;
    
    private Gtk.Action quitAction;
    
    private Gtk.Action AyudaAction;
    
    private Gtk.Action helpAction;
    
    private Gtk.Action homeAction;
    
    private Gtk.Action missingImageAction;
    
    private Gtk.Action aboutAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.EventBox _main_container;
    
    private Gtk.Statusbar statusbar;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.ArchivoAction = new Gtk.Action("ArchivoAction", Mono.Unix.Catalog.GetString("_Archivo"), null, null);
        this.ArchivoAction.ShortLabel = Mono.Unix.Catalog.GetString("_Archivo");
        w1.Add(this.ArchivoAction, null);
        this.quitAction = new Gtk.Action("quitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
        this.quitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w1.Add(this.quitAction, null);
        this.AyudaAction = new Gtk.Action("AyudaAction", Mono.Unix.Catalog.GetString("_Ayuda"), null, null);
        this.AyudaAction.ShortLabel = Mono.Unix.Catalog.GetString("_Ayuda");
        w1.Add(this.AyudaAction, null);
        this.helpAction = new Gtk.Action("helpAction", Mono.Unix.Catalog.GetString("_Temas de ayuda..."), null, "gtk-help");
        this.helpAction.ShortLabel = Mono.Unix.Catalog.GetString("_Temas de ayuda...");
        w1.Add(this.helpAction, null);
        this.homeAction = new Gtk.Action("homeAction", Mono.Unix.Catalog.GetString("_Sitio del proyecto"), null, "gtk-home");
        this.homeAction.ShortLabel = Mono.Unix.Catalog.GetString("_Sitio del proyecto");
        w1.Add(this.homeAction, null);
        this.missingImageAction = new Gtk.Action("missingImageAction", Mono.Unix.Catalog.GetString("_Reportar un error"), null, "gtk-missing-image");
        this.missingImageAction.ShortLabel = Mono.Unix.Catalog.GetString("_Reportar un error");
        w1.Add(this.missingImageAction, null);
        this.aboutAction = new Gtk.Action("aboutAction", Mono.Unix.Catalog.GetString("_Acerca de..."), null, "gtk-about");
        this.aboutAction.ShortLabel = Mono.Unix.Catalog.GetString("_Acerca de...");
        w1.Add(this.aboutAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='ArchivoAction' action='ArchivoAction'><menuitem name='quitAction' action='quitAction'/></menu><menu name='AyudaAction' action='AyudaAction'><menuitem name='helpAction' action='helpAction'/><separator/><menuitem name='homeAction' action='homeAction'/><menuitem name='missingImageAction' action='missingImageAction'/><separator/><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this._main_container = new Gtk.EventBox();
        this._main_container.Name = "_main_container";
        this.vbox1.Add(this._main_container);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this._main_container]));
        w3.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar = new Gtk.Statusbar();
        this.statusbar.Name = "statusbar";
        this.statusbar.Spacing = 6;
        this.vbox1.Add(this.statusbar);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar]));
        w4.Position = 2;
        w4.Expand = false;
        w4.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 442;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.quitAction.Activated += new System.EventHandler(this.OnQuitActionActivated);
        this.aboutAction.Activated += new System.EventHandler(this.OnAboutActionActivated);
    }
}
